const worlds = [
  {name:'Лесная тропа', ages:'Дошкольники · первые слова', icon:'🦊', character:'🦊', heroName:'Лисёнок Рыжик', intro:'Привет! Я Рыжик. Помоги мне пройти лес и найти домик. За верное слово мы идём вперёд, а после ошибки пробуем ещё раз.', destination:'🏡', setting:'forest', image:'forest-map.png', steps:4, lessons:[
    {id:'letters-ag',name:'Буквы A–G',icon:'🔤',mode:'letters',tip:'Нажми 🔊, послушай букву и найди её среди карточек.',items:[['A','a','🍎'],['B','b','🐝'],['C','c','🐱'],['D','d','🐶'],['E','e','🥚'],['F','f','🐟'],['G','g','🎁']]},
    {id:'letters-hn',name:'Буквы H–N',icon:'🔤',mode:'letters',tip:'Слушай букву и нажимай на подходящую карточку.',items:[['H','h','🏠'],['I','i','🍦'],['J','j','🧃'],['K','k','🪁'],['L','l','🦁'],['M','m','🌙'],['N','n','👃']]},
    {id:'letters-ot',name:'Буквы O–T',icon:'🔤',mode:'letters',tip:'Слушай букву и найди её маленькую пару.',items:[['O','o','🍊'],['P','p','🐧'],['Q','q','👑'],['R','r','🐰'],['S','s','☀️'],['T','t','🌳']]},
    {id:'letters-uz',name:'Буквы U–Z',icon:'🔤',mode:'letters',tip:'У всех 26 английских букв есть большая и маленькая формы.',items:[['U','u','☂️'],['V','v','🚐'],['W','w','🐋'],['X','x','🎹'],['Y','y','🪀'],['Z','z','🦓']]},
    {id:'numbers-0-10',name:'Считаем 0–10',icon:'🧮',mode:'count',tip:'Посчитай предметы и выбери число. Нажми 🔊, чтобы его услышать.',items:[['zero','0','🧺'],['one','1','🍎'],['two','2','🍎🍎'],['three','3','🍎🍎🍎'],['four','4','🍎🍎🍎🍎'],['five','5','🍎🍎🍎🍎🍎'],['six','6','🍎🍎🍎🍎🍎🍎'],['seven','7','🍎🍎🍎🍎🍎🍎🍎'],['eight','8','🍎🍎🍎🍎🍎🍎🍎🍎'],['nine','9','🍎🍎🍎🍎🍎🍎🍎🍎🍎'],['ten','10','🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎']]},
    {id:'numbers-11-20',name:'Числа 11–20',icon:'🎲',mode:'numbers',tip:'Нажми 🔊, послушай английское число и найди его запись.',items:[['eleven','11','🟡'],['twelve','12','🟢'],['thirteen','13','🔵'],['fourteen','14','🟣'],['fifteen','15','🟠'],['sixteen','16','🔴'],['seventeen','17','🟡'],['eighteen','18','🟢'],['nineteen','19','🔵'],['twenty','20','⭐']]},
    {id:'numbers-tens',name:'Десятки до 100',icon:'💯',mode:'numbers',tip:'Слушай английские числа: 20, 30, 40… до 100.',items:[['twenty','20','⭐'],['thirty','30','⭐'],['forty','40','⭐'],['fifty','50','⭐'],['sixty','60','⭐'],['seventy','70','⭐'],['eighty','80','⭐'],['ninety','90','⭐'],['one hundred','100','🏆']]},
    {id:'colors',name:'Цвета',icon:'🎨',tip:'Посмотри на цвет кружка и послушай английское слово.',items:[['red','красный','🔴'],['blue','синий','🔵'],['green','зелёный','🟢'],['yellow','жёлтый','🟡'],['orange','оранжевый','🟠'],['purple','фиолетовый','🟣'],['black','чёрный','⚫'],['white','белый','⚪']]},
    {id:'animals',name:'Животные',icon:'🐾',tip:'Подсказка: рисунок помогает вспомнить английское название животного.',items:[['cat','кошка','🐱'],['dog','собака','🐶'],['bird','птица','🐦'],['fish','рыба','🐟'],['fox','лиса','🦊'],['bear','медведь','🐻'],['rabbit','кролик','🐰'],['frog','лягушка','🐸']]},
    {id:'clothes',name:'Одежда',icon:'👕',tip:'Назови предмет одежды и послушай, как он звучит по-английски.',items:[['hat','шапка','🧢'],['shirt','рубашка','👕'],['dress','платье','👗'],['shoes','обувь','👟'],['socks','носки','🧦'],['coat','пальто','🧥'],['scarf','шарф','🧣'],['gloves','перчатки','🧤']]},
    {id:'little-actions',name:'Действия',icon:'🤸',tip:'Действие отвечает на вопрос «что делать?».',items:[['run','бежать','🏃'],['jump','прыгать','🤸'],['sleep','спать','😴'],['eat','есть','🍽️'],['read','читать','📖'],['sing','петь','🎤'],['swim','плавать','🏊'],['dance','танцевать','💃']]},
    {id:'numbers',name:'Первые числа',icon:'🔢',tip:'Посчитай от one до four: один, два, три, четыре.',items:[['one','один','1️⃣'],['two','два','2️⃣'],['three','три','3️⃣'],['four','четыре','4️⃣']]},
    {id:'family',name:'Семья',icon:'🏠',tip:'Mother и father — родители; sister и brother — сестра и брат.',items:[['mother','мама','👩'],['father','папа','👨'],['sister','сестра','👧'],['brother','брат','👦']]},
    {id:'school',name:'Школа',icon:'✏️',tip:'Посмотри на картинку школьного предмета и послушай его название.',items:[['book','книга','📚'],['pen','ручка','🖊️'],['bag','сумка','🎒'],['desk','парта','🪑']]}
  ]},
  {name:'Город робота', ages:'1–2 класс · слова и короткие фразы', icon:'🤖', character:'🤖', heroName:'Робот Бип', intro:'Привет! Я Бип. Мы исследуем город и доберёмся до замка. Ты подскажешь мне английские слова и фразы?', destination:'🏰', setting:'city', image:'city-map.png', steps:6, lessons:[
    {id:'grade12-food',name:'Перекус',icon:'🍎',tip:'Слушай слово, затем найди его перевод.',items:[['apple','яблоко','🍎'],['bread','хлеб','🍞'],['cheese','сыр','🧀'],['carrot','морковь','🥕'],['milk','молоко','🥛'],['banana','банан','🍌']]},
    {id:'grade12-places',name:'В городе',icon:'🏙️',tip:'Where is…? означает «Где…?».',items:[['a park','парк','🌳'],['a shop','магазин','🏬'],['a school','школа','🏫'],['a library','библиотека','📚'],['a hospital','больница','🏥'],['a museum','музей','🏛️']]},
    {id:'grade12-actions',name:'Что я умею',icon:'⚡',tip:'I can означает «я умею».',items:[['I can read.','Я умею читать.','📖'],['I can swim.','Я умею плавать.','🏊'],['I can sing.','Я умею петь.','🎤'],['I can draw.','Я умею рисовать.','🎨'],['I can skate.','Я умею кататься на коньках.','⛸️'],['I can cook.','Я умею готовить.','🍳']]},
    {id:'grade12-weather',name:'Погода',icon:'☀️',tip:'It is — «сейчас…»; дальше можно назвать погоду.',items:[['It is sunny.','Солнечно.','☀️'],['It is rainy.','Дождливо.','🌧️'],['It is windy.','Ветрено.','🌬️'],['It is snowy.','Снежно.','❄️'],['It is cloudy.','Облачно.','☁️'],['It is hot.','Жарко.','🥵']]},
    {id:'grade12-feelings',name:'Как дела?',icon:'🙂',tip:'I am означает «я…»; после него можно сказать, как себя чувствуешь.',items:[['I am happy.','Я рад.','😄'],['I am tired.','Я устал.','😴'],['I am hungry.','Я голоден.','😋'],['I am cold.','Мне холодно.','🥶'],['I am sad.','Мне грустно.','😢'],['I am excited.','Я взволнован.','🤩']]}
  ]},
  {name:'Космическая экспедиция', ages:'3–4 класс · предложения и вопросы', icon:'🚀', character:'👩‍🚀', heroName:'Космонавт Луна', intro:'Привет! Я Луна. Впереди космическая экспедиция к новой планете. Помоги мне понять английские предложения!', destination:'🪐', setting:'space', image:'space-map.png', steps:8, lessons:[
    {id:'grade34-routine',name:'Мой день',icon:'🕒',tip:'В Present Simple с he и she к глаголу обычно добавляем -s.',items:[['She gets up at seven.','Она встаёт в семь.'],['He goes to school by bus.','Он едет в школу на автобусе.'],['We have lunch at one.','Мы обедаем в час.'],['They play after school.','Они играют после школы.'],['I brush my teeth in the morning.','Я чищу зубы утром.'],['She does her homework in the evening.','Она делает домашнее задание вечером.'],['He walks his dog every day.','Он гуляет с собакой каждый день.'],['We go to bed at nine.','Мы ложимся спать в девять.']]},
    {id:'grade34-questions',name:'Вопросы о себе',icon:'❔',tip:'В вопросах с you часто используем do: Do you like…?',items:[['Do you like music?','Тебе нравится музыка?'],['Where do you live?','Где ты живёшь?'],['What time is it?','Который час?'],['Can you ride a bike?','Ты умеешь кататься на велосипеде?'],['What is your favourite game?','Какая твоя любимая игра?'],['How old is your brother?','Сколько лет твоему брату?'],['Does she speak English?','Она говорит по-английски?'],['When do you get up?','Когда ты встаёшь?']]},
    {id:'grade34-present',name:'Сейчас или обычно?',icon:'⏳',tip:'I read — обычно. I am reading — прямо сейчас.',items:[['I read every day.','Я читаю каждый день.'],['I am reading now.','Я читаю сейчас.'],['She plays on Sundays.','Она играет по воскресеньям.'],['She is playing now.','Она играет сейчас.'],['They walk to school on Mondays.','Они ходят в школу пешком по понедельникам.'],['They are walking to school now.','Они идут в школу пешком сейчас.'],['He draws pictures every week.','Он рисует картины каждую неделю.'],['He is drawing a picture.','Он рисует картину сейчас.']]},
    {id:'grade34-possessive',name:'Чьи это вещи?',icon:'🎒',tip:'My — мой, his — его, her — её, our — наш.',items:[['This is my pencil.','Это мой карандаш.'],['That is his jacket.','Это его куртка.'],['Her bag is blue.','Её сумка синяя.'],['Our classroom is big.','Наш класс большой.'],['Your book is on the table.','Твоя книга на столе.'],['Their house is near the park.','Их дом рядом с парком.'],['These are my shoes.','Это мои туфли.'],['His bike is new.','Его велосипед новый.']]},
    {id:'grade34-past',name:'Что было вчера?',icon:'🕰️',tip:'Yesterday означает «вчера». В прошедшем времени play становится played, go — went.',items:[['I played yesterday.','Я играл вчера.'],['We went to the park.','Мы ходили в парк.'],['She watched a film.','Она посмотрела фильм.'],['He had a good day.','У него был хороший день.'],['They visited their grandparents.','Они навестили бабушку и дедушку.'],['I saw a rainbow.','Я увидел радугу.'],['She made a cake.','Она испекла торт.'],['He read a story last night.','Он прочитал рассказ вчера вечером.']]},
    {id:'grade34-bridge',name:'Собери предложение',icon:'🧱',tip:'Сначала выбери форму глагола, а затем собери целое предложение. Это подготовка к урокам 5–6 класса.',tasks:[
      {kind:'edit',sentence:'She ___ to school every day.',translation:'Она каждый день ходит в школу.',answer:'goes',choices:['go','goes','went','going'],explanation:'С she в Present Simple: go → goes.'},
      {kind:'edit',sentence:'They ___ playing now.',translation:'Они сейчас играют.',answer:'are',choices:['am','is','are','do'],explanation:'С they употребляем are: they are playing.'},
      {kind:'edit',sentence:'I ___ my friend yesterday.',translation:'Я вчера видел своего друга.',answer:'saw',choices:['see','sees','saw','seeing'],explanation:'Yesterday — прошлое время; see → saw.'},
      {kind:'edit',sentence:'___ you like cats?',translation:'Тебе нравятся кошки?',answer:'Do',choices:['Do','Does','Are','Is'],explanation:'Вопрос в Present Simple с you начинается с Do.'},
      {kind:'edit',sentence:'He ___ a new bike.',translation:'У него есть новый велосипед.',answer:'has',choices:['have','has','had','having'],explanation:'С he в настоящем времени ставим has.'},
      {kind:'edit',sentence:'We ___ to the park yesterday.',translation:'Мы вчера ходили в парк.',answer:'went',choices:['go','goes','went','going'],explanation:'Неправильный глагол: go → went.'},
      {kind:'order',translation:'Она сейчас читает книгу.',words:['She','is','reading','a','book','now.'],explanation:'Для действия прямо сейчас: she is reading.'},
      {kind:'order',translation:'Мы видели собаку вчера.',words:['We','saw','a','dog','yesterday.'],explanation:'Прошедшая форма see — saw.'}
    ]}
  ]},
  {name:'Средняя школа I', ages:'5–6 класс · времена и общение', icon:'📗', lessons:[
    {id:'grade56-past',name:'Прошедшее время',icon:'⌛',tip:'В Past Simple правильный глагол получает -ed, а неправильные формы нужно запомнить.',items:[['I visited my grandma.','Я навестил бабушку.'],['She bought a ticket.','Она купила билет.'],['They saw a rainbow.','Они увидели радугу.'],['We did our homework.','Мы сделали домашнее задание.']]},
    {id:'grade56-future',name:'Планы на будущее',icon:'📅',tip:'Be going to выражает план, а will часто помогает сказать о решении или предположении.',items:[['I am going to study tonight.','Я собираюсь заниматься сегодня вечером.'],['She will call you later.','Она позвонит тебе позже.'],['We are going to travel in July.','Мы собираемся путешествовать в июле.'],['It will probably rain.','Вероятно, будет дождь.']]},
    {id:'grade56-comparison',name:'Сравниваем',icon:'⚖️',tip:'Сравнительная степень: tall → taller, good → better.',items:[['This book is more interesting.','Эта книга интереснее.'],['My room is smaller.','Моя комната меньше.'],['Today is warmer than yesterday.','Сегодня теплее, чем вчера.'],['This answer is better.','Этот ответ лучше.']]},
    {id:'grade56-modals',name:'Можно и нужно',icon:'🧩',tip:'Can — могу, must — должен, should — стоит, may — можно.',items:[['You should drink water.','Тебе стоит пить воду.'],['We must be careful.','Мы должны быть осторожны.'],['Can I ask a question?','Можно задать вопрос?'],['She may come later.','Возможно, она придёт позже.']]},
    {id:'grade56-dialogue',name:'Полезные фразы',icon:'💬',tip:'Выбирай перевод всей фразы, а не отдельного слова.',items:[['Could you help me, please?','Не могли бы вы мне помочь?'],['How much does it cost?','Сколько это стоит?'],['I would like a cup of tea.','Я бы хотел чашку чая.'],['Where is the nearest station?','Где ближайшая станция?']]},
    {id:'grade56-workshop',name:'Мастерская предложений',icon:'🧱',tip:'Подставь слово в предложение или собери слова в нужном порядке.',tasks:[
      {kind:'edit',sentence:'My sister ___ English every day.',translation:'Моя сестра учит английский каждый день.',answer:'studies',choices:['study','studies','studying','studied'],explanation:'С she в Present Simple нужен глагол с -s; study меняет -y на -ies.'},
      {kind:'edit',sentence:'We met ___ the bus stop.',translation:'Мы встретились на автобусной остановке.',answer:'at',choices:['in','on','at','to'],explanation:'At указывает на конкретное место встречи.'},
      {kind:'edit',sentence:'They ___ to the museum yesterday.',translation:'Они ходили в музей вчера.',answer:'went',choices:['go','goes','going','went'],explanation:'Yesterday указывает на прошлое; прошедшая форма go — went.'},
      {kind:'edit',sentence:'There ___ three apples on the table.',translation:'На столе три яблока.',answer:'are',choices:['is','are','am','be'],explanation:'Three apples — множественное число, поэтому there are.'},
      {kind:'edit',sentence:'I am going ___ visit my aunt.',translation:'Я собираюсь навестить тётю.',answer:'to',choices:['for','at','to','with'],explanation:'Для плана используем be going to + глагол.'},
      {kind:'edit',sentence:'He ___ like cold weather.',translation:'Он не любит холодную погоду.',answer:'doesn’t',choices:['don’t','doesn’t','isn’t','didn’t'],explanation:'He в Present Simple требует doesn’t; после него like без -s.'},
      {kind:'order',translation:'Она вчера купила новую книгу.',words:['She','bought','a','new','book','yesterday.'],explanation:'В Past Simple: подлежащее + bought + дополнение; yesterday ставим в конце.'},
      {kind:'order',translation:'Мы собираемся играть после школы.',words:['We','are','going','to','play','after','school.'],explanation:'План строится как are going to + play.'}
    ]},
    {id:'grade56-have',name:'Have, has и had',icon:'⏳',tip:'I/you/we/they → have; he/she/it → has. Had — прошедшее время для всех лиц.',tasks:[
      {kind:'edit',sentence:'I ___ a new bicycle.',translation:'У меня есть новый велосипед.',answer:'have',choices:['has','have','had','having'],explanation:'С I в настоящем времени ставим have.'},
      {kind:'edit',sentence:'She ___ two brothers.',translation:'У неё два брата.',answer:'has',choices:['have','has','had','having'],explanation:'С she в настоящем времени ставим has.'},
      {kind:'edit',sentence:'They ___ a music lesson on Fridays.',translation:'У них урок музыки по пятницам.',answer:'have',choices:['had','has','have','having'],explanation:'С they в настоящем времени ставим have.'},
      {kind:'edit',sentence:'My dog ___ a long tail.',translation:'У моей собаки длинный хвост.',answer:'has',choices:['have','has','had','having'],explanation:'My dog = it, поэтому has.'},
      {kind:'edit',sentence:'We ___ a great time yesterday.',translation:'Мы отлично провели время вчера.',answer:'had',choices:['have','has','had','having'],explanation:'Yesterday указывает на прошлое: have/has превращается в had.'},
      {kind:'edit',sentence:'___ he got a pencil?',translation:'У него есть карандаш?',answer:'Has',choices:['Have','Has','Had','Having'],explanation:'В вопросе с he: Has he got ... ?'},
      {kind:'edit',sentence:'I ___ finished my homework.',translation:'Я уже закончил домашнее задание.',answer:'have',choices:['has','have','had','having'],explanation:'В Present Perfect с I: have + третья форма finished.'},
      {kind:'edit',sentence:'She ___ already eaten lunch.',translation:'Она уже пообедала.',answer:'has',choices:['have','has','had','having'],explanation:'В Present Perfect с she: has + третья форма eaten.'},
      {kind:'edit',sentence:'He ___ a cold last week.',translation:'На прошлой неделе он простудился.',answer:'had',choices:['has','have','had','having'],explanation:'Last week — прошлое, значит had.'},
      {kind:'edit',sentence:'You ___ got a beautiful drawing.',translation:'У тебя красивый рисунок.',answer:'have',choices:['has','had','have','having'],explanation:'С you всегда используем have.'},
      {kind:'order',translation:'У неё есть новый велосипед.',words:['She','has','a','new','bicycle.'],explanation:'С she используем has.'},
      {kind:'order',translation:'Вчера у нас был урок.',words:['We','had','a','lesson','yesterday.'],explanation:'В прошедшем времени для всех лиц ставим had.'}
    ]}
  ]},
  {name:'Средняя школа II', ages:'7–9 класс · сложные конструкции', icon:'🧭', lessons:[
    {id:'grade79-perfect',name:'Present Perfect',icon:'✔️',tip:'Have/has + третья форма: важен результат к настоящему моменту.',items:[['I have already finished.','Я уже закончил.'],['She has never been there.','Она никогда там не была.'],['We have just arrived.','Мы только что приехали.'],['They have lost the keys.','Они потеряли ключи.']]},
    {id:'grade79-conditional',name:'Если…, то…',icon:'🔀',tip:'В реальном условии: If + Present Simple, затем will.',items:[['If it rains, we will stay home.','Если пойдёт дождь, мы останемся дома.'],['If I finish early, I will call you.','Если я закончу рано, я тебе позвоню.'],['If she studies, she will pass.','Если она будет заниматься, она сдаст экзамен.'],['If you hurry, you will catch the bus.','Если ты поторопишься, успеешь на автобус.']]},
    {id:'grade79-passive',name:'Страдательный залог',icon:'🔧',tip:'Be + третья форма: действие направлено на предмет.',items:[['The bridge was built in 1990.','Мост был построен в 1990 году.'],['English is spoken here.','Здесь говорят по-английски.'],['The letter was sent yesterday.','Письмо было отправлено вчера.'],['These books are made for children.','Эти книги созданы для детей.']]},
    {id:'grade79-reported',name:'Передаём чужие слова',icon:'🗣️',tip:'В косвенной речи после said время часто сдвигается назад.',items:[['He said he was tired.','Он сказал, что устал.'],['She told me she liked it.','Она сказала мне, что ей это нравилось.'],['They said they would come.','Они сказали, что придут.'],['I asked where she lived.','Я спросил, где она жила.']]},
    {id:'grade79-clauses',name:'Связь мыслей',icon:'🔗',tip:'Although — хотя; because — потому что; while — в то время как.',items:[['Although it was late, we continued.','Хотя было поздно, мы продолжили.'],['I stayed home because I was ill.','Я остался дома, потому что заболел.'],['She listened while he spoke.','Она слушала, пока он говорил.'],['We left before the film ended.','Мы ушли до того, как фильм закончился.']]},
    {id:'grade79-workshop',name:'Мастерская предложений',icon:'🧱',tip:'Восстанови фразу: важны время, предлог и порядок слов.',tasks:[
      {kind:'edit',sentence:'She has lived here ___ 2020.',translation:'Она живёт здесь с 2020 года.',answer:'since',choices:['for','since','during','from'],explanation:'Since ставим перед точкой отсчёта — годом 2020; for — перед длительностью.'},
      {kind:'edit',sentence:'If it rains, we ___ at home.',translation:'Если пойдёт дождь, мы останемся дома.',answer:'will stay',choices:['stayed','will stay','staying','would stay'],explanation:'В реальном условии после if — Present Simple, в главной части — will.'},
      {kind:'edit',sentence:'The letter was ___ yesterday.',translation:'Письмо было отправлено вчера.',answer:'sent',choices:['send','sending','sent','sends'],explanation:'Пассивный залог в прошлом: was + третья форма глагола.'},
      {kind:'edit',sentence:'He said that he ___ tired.',translation:'Он сказал, что устал.',answer:'was',choices:['is','were','was','be'],explanation:'После said в косвенной речи is обычно меняется на was.'},
      {kind:'edit',sentence:'I’m interested ___ science.',translation:'Меня интересует наука.',answer:'in',choices:['at','on','in','for'],explanation:'Устойчивое сочетание: interested in.'},
      {kind:'edit',sentence:'This is the film ___ we watched last night.',translation:'Это фильм, который мы смотрели вчера вечером.',answer:'that',choices:['who','whose','where','that'],explanation:'That связывает часть предложения с предметом — film.'},
      {kind:'order',translation:'Если ты поторопишься, то успеешь на автобус.',words:['If','you','hurry,','you','will','catch','the','bus.'],explanation:'После if глагол hurry в настоящем, затем will catch.'},
      {kind:'order',translation:'Эта книга была написана в 2010 году.',words:['This','book','was','written','in','2010.'],explanation:'В пассивном залоге прошедшего времени: was written.'}
    ]},
    {id:'grade79-tenses',name:'Have, has и времена',icon:'🕒',tip:'Present Perfect: have/has + третья форма. Past Perfect: had + третья форма.',tasks:[
      {kind:'edit',sentence:'He ___ just arrived.',translation:'Он только что приехал.',answer:'has',choices:['have','has','had','is'],explanation:'He в Present Perfect сочетается с has.'},
      {kind:'edit',sentence:'We ___ already seen this film.',translation:'Мы уже видели этот фильм.',answer:'have',choices:['has','have','had','are'],explanation:'We в Present Perfect сочетается с have.'},
      {kind:'edit',sentence:'She has ___ her keys.',translation:'Она потеряла ключи.',answer:'lost',choices:['lose','losing','lost','loses'],explanation:'После has нужна третья форма: lose → lost.'},
      {kind:'edit',sentence:'I have lived here ___ three years.',translation:'Я живу здесь три года.',answer:'for',choices:['since','for','during','from'],explanation:'For ставим перед длительностью — three years.'},
      {kind:'edit',sentence:'They have known him ___ 2021.',translation:'Они знают его с 2021 года.',answer:'since',choices:['for','since','during','by'],explanation:'Since ставим перед точкой отсчёта — годом.'},
      {kind:'edit',sentence:'By the time we got there, the train ___ left.',translation:'Когда мы добрались, поезд уже ушёл.',answer:'had',choices:['has','have','had','was'],explanation:'Поезд ушёл раньше другого события в прошлом: had left.'},
      {kind:'edit',sentence:'___ you ever visited London?',translation:'Ты когда-нибудь бывал в Лондоне?',answer:'Have',choices:['Has','Have','Had','Did'],explanation:'Вопрос к you в Present Perfect начинается с Have.'},
      {kind:'edit',sentence:'She ___ not finished yet.',translation:'Она ещё не закончила.',answer:'has',choices:['have','has','had','does'],explanation:'Yet в этом контексте подходит к Present Perfect: has not finished.'},
      {kind:'edit',sentence:'When I called, they ___ already gone.',translation:'Когда я позвонил, они уже ушли.',answer:'had',choices:['have','has','had','were'],explanation:'Они ушли раньше звонка: had gone.'},
      {kind:'edit',sentence:'I ___ never eaten sushi.',translation:'Я никогда не ел суши.',answer:'have',choices:['has','have','had','am'],explanation:'Опыт к настоящему моменту: I have never eaten.'},
      {kind:'order',translation:'Она уже потеряла ключи.',words:['She','has','already','lost','her','keys.'],explanation:'Present Perfect: has + третья форма lost.'},
      {kind:'order',translation:'Когда я пришёл, они уже ушли.',words:['When','I','arrived,','they','had','already','left.'],explanation:'Действие had left произошло раньше I arrived.'}
    ]}
  ]},
  {name:'Старшая школа', ages:'10–11 класс · высокий уровень', icon:'👑', lessons:[
    {id:'grade1011-conditionals',name:'Нереальные условия',icon:'💭',tip:'If I were… I would… помогает представить нереальную ситуацию.',items:[['If I were you, I would wait.','На твоём месте я бы подождал.'],['If she had time, she would join us.','Если бы у неё было время, она бы присоединилась.'],['If we had left earlier, we would have arrived on time.','Если бы мы вышли раньше, мы бы прибыли вовремя.'],['If he knew the answer, he would tell us.','Если бы он знал ответ, он бы нам сказал.']]},
    {id:'grade1011-perfect',name:'Времена в контексте',icon:'⏱️',tip:'Past Perfect обозначает действие, которое произошло раньше другого события в прошлом.',items:[['By the time I arrived, they had left.','К тому времени, как я пришёл, они уже ушли.'],['She had been waiting for an hour.','Она ждала уже целый час.'],['He has been studying all morning.','Он занимается всё утро.'],['They will have finished by Friday.','Они закончат к пятнице.']]},
    {id:'grade1011-argument',name:'Выражаем мнение',icon:'📝',tip:'Слова-связки помогают строить аргумент: however, therefore, despite.',items:[['However, the results were different.','Однако результаты оказались другими.'],['Therefore, we changed our plan.','Поэтому мы изменили план.'],['Despite the rain, the event took place.','Несмотря на дождь, мероприятие состоялось.'],['Moreover, the solution is affordable.','Более того, это решение доступно по цене.']]},
    {id:'grade1011-relative',name:'Сложные предложения',icon:'🧠',tip:'Which, who и whose добавляют информацию о предмете или человеке.',items:[['The girl who won is my friend.','Девочка, которая победила, — моя подруга.'],['The book, which I borrowed, was useful.','Книга, которую я одолжил, оказалась полезной.'],['The man whose car broke down called us.','Мужчина, чья машина сломалась, позвонил нам.'],['This is the place where we met.','Это место, где мы встретились.']]},
    {id:'grade1011-nuance',name:'Точный смысл',icon:'🎯',tip:'Внимательно смотри на смысл модальных конструкций, а не на отдельные слова.',items:[['She might have missed the train.','Возможно, она опоздала на поезд.'],['You need not have bought it.','Тебе не нужно было это покупать.'],['He must have forgotten the meeting.','Должно быть, он забыл о встрече.'],['They should have told us earlier.','Им следовало сказать нам раньше.']]},
    {id:'grade1011-workshop',name:'Мастерская предложений',icon:'🧱',tip:'Измени форму слова и собери сложную мысль без потери смысла.',tasks:[
      {kind:'edit',sentence:'If I had known, I ___ you.',translation:'Если бы я знал, я бы тебе помог.',answer:'would have helped',choices:['will help','would help','would have helped','had helped'],explanation:'Нереальное условие в прошлом: if + had known, затем would have + третья форма.'},
      {kind:'edit',sentence:'Despite ___ tired, she kept working.',translation:'Несмотря на усталость, она продолжала работать.',answer:'being',choices:['be','being','was','been'],explanation:'После despite нужен существительное или форма глагола с -ing.'},
      {kind:'edit',sentence:'The student ___ essay won the prize is here.',translation:'Ученик, чьё сочинение получило приз, здесь.',answer:'whose',choices:['who','which','whose','where'],explanation:'Whose показывает принадлежность: чьё сочинение.'},
      {kind:'edit',sentence:'By next June, she ___ the course.',translation:'К следующему июню она уже закончит курс.',answer:'will have completed',choices:['has completed','had completed','will complete','will have completed'],explanation:'By next June задаёт срок в будущем; Future Perfect показывает результат к этому сроку.'},
      {kind:'edit',sentence:'You ___ told me earlier; now it is too late.',translation:'Тебе следовало сказать мне раньше; теперь слишком поздно.',answer:'should have',choices:['must have','should have','may have','will have'],explanation:'Should have + третья форма выражает сожаление о прошлом.'},
      {kind:'edit',sentence:'Hardly had we arrived ___ it started raining.',translation:'Едва мы приехали, как начался дождь.',answer:'when',choices:['than','when','while','until'],explanation:'Устойчивая конструкция: hardly ... when; no sooner ... than.'},
      {kind:'order',translation:'Если бы она занималась, то сдала бы экзамен.',words:['If','she','had','studied,','she','would','have','passed','the','exam.'],explanation:'Третье условное: had studied + would have passed.'},
      {kind:'order',translation:'Лишь тогда мы поняли свою ошибку.',words:['Only','then','did','we','realise','our','mistake.'],explanation:'После Only then в начале предложения нужна инверсия: did we realise.'}
    ]},
    {id:'grade1011-tenses',name:'Сложные времена',icon:'⌛',tip:'Смотри на временные указатели: уже, к тому времени, к сроку, как долго.',tasks:[
      {kind:'edit',sentence:'She ___ been working for two hours.',translation:'Она работает уже два часа.',answer:'has',choices:['have','has','had','will'],explanation:'Действие началось раньше и продолжается сейчас: has been working.'},
      {kind:'edit',sentence:'By the time the show started, we ___ taken our seats.',translation:'К началу представления мы уже заняли места.',answer:'had',choices:['have','has','had','will have'],explanation:'Одно прошедшее действие произошло раньше другого: had taken.'},
      {kind:'edit',sentence:'By next month, they ___ completed the project.',translation:'К следующему месяцу они завершат проект.',answer:'will have',choices:['have','had','will have','have been'],explanation:'Результат к будущему сроку: will have completed.'},
      {kind:'edit',sentence:'He ___ been studying when the lights went out.',translation:'Он занимался уже какое-то время, когда погас свет.',answer:'had',choices:['has','have','had','will have'],explanation:'Длительное действие до события в прошлом: had been studying.'},
      {kind:'edit',sentence:'They ___ been waiting since noon.',translation:'Они ждут с полудня.',answer:'have',choices:['has','have','had','will have'],explanation:'They в Present Perfect Continuous сочетается с have.'},
      {kind:'edit',sentence:'I ___ have forgotten her name.',translation:'Возможно, я забыл её имя.',answer:'might',choices:['must','should','might','would'],explanation:'Might have + третья форма выражает неуверенное предположение о прошлом.'},
      {kind:'edit',sentence:'She ___ have called us earlier.',translation:'Ей следовало позвонить нам раньше.',answer:'should',choices:['will','might','should','has'],explanation:'Should have + третья форма выражает сожаление или совет задним числом.'},
      {kind:'edit',sentence:'By 2030, he ___ been teaching for twenty years.',translation:'К 2030 году он будет преподавать уже двадцать лет.',answer:'will have',choices:['has','had','will have','would have'],explanation:'Future Perfect Continuous показывает длительность к моменту в будущем.'},
      {kind:'edit',sentence:'I have never ___ such a difficult puzzle.',translation:'Я никогда не решал такую сложную головоломку.',answer:'solved',choices:['solve','solving','solved','solves'],explanation:'После have в Present Perfect нужна третья форма — solved.'},
      {kind:'edit',sentence:'If we had left earlier, we ___ caught the train.',translation:'Если бы мы вышли раньше, мы бы успели на поезд.',answer:'would have',choices:['will have','would have','have','had'],explanation:'Нереальное условие в прошлом: had left + would have caught.'},
      {kind:'order',translation:'К пятнице они уже закончат проект.',words:['They','will','have','finished','the','project','by','Friday.'],explanation:'Will have finished — результат к сроку в будущем.'},
      {kind:'order',translation:'Если бы мы вышли раньше, мы бы успели на поезд.',words:['If','we','had','left','earlier,','we','would','have','caught','the','train.'],explanation:'Had left + would have caught — условие в прошлом.'}
    ]}
  ]}
];
const extraItems = {
  'grade56-past':[['He found his keys.','Он нашёл свои ключи.'],['They wrote a letter.','Они написали письмо.']],
  'grade56-future':[['We will meet tomorrow.','Мы встретимся завтра.'],['He is going to cook dinner.','Он собирается приготовить ужин.']],
  'grade56-comparison':[['This river is longer.','Эта река длиннее.'],['Her plan is easier.','Её план проще.']],
  'grade56-modals':[['You must wear a helmet.','Ты должен надеть шлем.'],['They can solve this problem.','Они могут решить эту задачу.']],
  'grade56-dialogue':[['What do you recommend?','Что вы посоветуете?'],['Could I have the menu, please?','Можно мне меню, пожалуйста?']],
  'grade79-perfect':[['He has broken his glasses.','Он сломал очки.'],['Have you ever tried it?','Ты когда-нибудь это пробовал?']],
  'grade79-conditional':[['If we miss the train, we will take a taxi.','Если мы опоздаем на поезд, возьмём такси.'],['If you practise, you will improve.','Если будешь тренироваться, станешь лучше.']],
  'grade79-passive':[['The cake was baked this morning.','Торт испекли сегодня утром.'],['The windows are cleaned every week.','Окна моют каждую неделю.']],
  'grade79-reported':[['She said she was busy.','Она сказала, что занята.'],['He told us he had a ticket.','Он сказал нам, что у него был билет.']],
  'grade79-clauses':[['Although it was cold, we went out.','Хотя было холодно, мы вышли.'],['We waited until the rain stopped.','Мы ждали, пока дождь не закончился.']],
  'grade1011-conditionals':[['If I had known, I would have helped.','Если бы я знал, я бы помог.'],['If she were here, she would understand.','Если бы она была здесь, она бы поняла.']],
  'grade1011-perfect':[['I had finished before she arrived.','Я закончил до того, как она пришла.'],['By Monday, we will have prepared everything.','К понедельнику мы всё подготовим.']],
  'grade1011-argument':[['Nevertheless, we decided to continue.','Тем не менее мы решили продолжить.'],['In addition, the plan saves time.','Кроме того, этот план экономит время.']],
  'grade1011-relative':[['The teacher whose class won was delighted.','Учитель, чей класс победил, был рад.'],['The city where I grew up has changed.','Город, в котором я вырос, изменился.']],
  'grade1011-nuance':[['He cannot have seen us.','Он никак не мог нас увидеть.'],['She could have asked for help.','Она могла бы попросить о помощи.']]
};
const exceptions = {
  'grade34-routine':[['go → goes','ходит','После he/she у go добавляется -es.'],['do → does','делает','После he/she у do особая форма does.']],
  'grade34-past':[['go → went','идти → ходил','В прошлом go не превращается в goed.'],['see → saw','видеть → видел','Прошедшая форма see — saw.'],['have → had','иметь → имел','Had — прошедшая форма have и has.'],['read → read','читать → читал','Пишется одинаково, но в прошлом произносится как «ред».']],
  'grade34-bridge':[['go → went','идти → ходил','Went пригодится в последнем задании.'],['see → saw','видеть → видел','Saw пригодится при сборке предложения.']],
  'grade56-past':[['buy → bought','покупать → купил','В прошлом не говорим buyed.'],['write → wrote','писать → написал','Прошедшая форма write — wrote.'],['find → found','находить → нашёл','Прошедшая форма find — found.']],
  'grade56-comparison':[['good → better','хороший → лучше','Сравнительная степень не gooder.']],
  'grade56-have':[['have / has → had','иметь → имел','В прошлом для всех лиц одна форма — had.'],['eat → ate → eaten','есть → ел → съеденный','После has в Present Perfect нужна третья форма eaten.']],
  'grade79-perfect':[['be → was/were → been','быть → был → был','После have/has используем been.'],['break → broke → broken','ломать → сломал → сломанный','После has нужна третья форма broken.']],
  'grade79-passive':[['build → built → built','строить → построил → построенный','В пассивном залоге: was built.'],['send → sent → sent','отправлять → отправил → отправленный','В пассивном залоге: was sent.']],
  'grade1011-conditionals':[['be → were','быть → был бы','В условии If I were you употребляем were.']],
  'grade1011-tenses':[['leave → left → left','уходить → ушёл → ушедший','После had нужна третья форма left.']]
};
const itemBank=lesson=>[...lesson.items,...(extraItems[lesson.id]||[])];
const explanations = {
  'If I were you, I would wait.':'If I were you — «на твоём месте». Would выражает совет в воображаемой ситуации.',
  'If she had time, she would join us.':'Had здесь означает воображаемое условие: сейчас у неё нет времени.',
  'If we had left earlier, we would have arrived on time.':'Had left + would have arrived: оба действия относятся к прошлому, которое уже не изменить.',
  'If he knew the answer, he would tell us.':'Knew + would tell: он не знает ответ сейчас, поэтому условие нереальное.',
  'By the time I arrived, they had left.':'Had left произошло раньше, чем I arrived.',
  'She had been waiting for an hour.':'Had been waiting подчёркивает длительность ожидания до момента в прошлом.',
  'He has been studying all morning.':'Has been studying: начал утром и продолжает заниматься или только что закончил.',
  'They will have finished by Friday.':'Will have finished означает, что к пятнице работа уже будет завершена.',
  'However, the results were different.':'However вводит противопоставление: «однако».',
  'Therefore, we changed our plan.':'Therefore указывает на следствие: «поэтому».',
  'Despite the rain, the event took place.':'Despite значит «несмотря на»; после него стоит существительное the rain.',
  'Moreover, the solution is affordable.':'Moreover добавляет аргумент: «более того». Affordable — «доступный по цене».',
  'The girl who won is my friend.':'Who относится к человеку: победила именно девочка.',
  'The book, which I borrowed, was useful.':'Which относится к книге; I borrowed уточняет, о какой книге речь.',
  'The man whose car broke down called us.':'Whose означает «чей»: сломалась машина этого мужчины.',
  'This is the place where we met.':'Where связывает место и действие: «место, где мы встретились».',
  'She might have missed the train.':'Might have + третья форма выражает неуверенное предположение о прошлом.',
  'You need not have bought it.':'Need not have означает: купил, хотя необходимости в этом не было.',
  'He must have forgotten the meeting.':'Must have + третья форма — уверенное предположение о прошлом.',
  'They should have told us earlier.':'Should have — сожаление или упрёк: им следовало сказать раньше.'
};
const lessons = worlds.flatMap(w=>w.lessons);
const awards = [
  {id:'first',icon:'🌱',name:'Первый шаг',hint:'Пройди первый урок',check:s=>done(s)>=1},
  {id:'five',icon:'🧭',name:'Исследователь',hint:'Пройди 5 уроков',check:s=>done(s)>=5},
  {id:'stars',icon:'✨',name:'Звёздный герой',hint:'Собери 15 звёзд',check:s=>total(s)>=15},
  {id:'perfect',icon:'💎',name:'Без ошибок',hint:'Пройди урок без ошибок',check:s=>Object.values(s.scores).some(x=>x===3)},
  {id:'middle',icon:'🚀',name:'Новая планета',hint:'Пройди урок 5–6 класса',check:s=>worlds[3].lessons.some(l=>s.scores[l.id])},
  {id:'master',icon:'👑',name:'Мастер английского',hint:'Пройди все уроки',check:s=>done(s)===lessons.length}
];
function load(){try{const x=JSON.parse(localStorage.getItem('slovolet-v1'));return {scores:x&&typeof x.scores==='object'&&!Array.isArray(x.scores)?x.scores:{},errors:x?.errors&&typeof x.errors==='object'&&!Array.isArray(x.errors)?x.errors:{},bonus:Number(x?.bonus)||0,lastDay:typeof x?.lastDay==='string'?x.lastDay:'',streak:Number(x?.streak)||0,sound:x?.sound!==false}}catch{return {scores:{},errors:{},bonus:0,lastDay:'',streak:0,sound:true}}}
function readSession(){try{
 const raw=JSON.parse(localStorage.getItem('slovolet-session-v1'));if(!raw||typeof raw.lessonId!=='string')return null;
 const lesson=lessons.find(l=>l.id===raw.lessonId);if(!lesson)return null;const world=worlds.find(w=>w.lessons.includes(lesson));
 const question=q=>{if(!q||typeof q.english!=='string')return null;
  if(lesson.tasks){const task=lesson.tasks[q.taskIndex];if(!task||q.kind!==task.kind||!Array.isArray(q.choices)||q.choices.length!==(task.kind==='edit'?4:task.words.length))return null;
   const expected=task.kind==='edit'?task.choices:task.words;if([...q.choices].sort().join('\u0000')!==[...expected].sort().join('\u0000'))return null;
   const answer=task.kind==='edit'?task.answer:task.words.join(' ');if(q.english!==(task.kind==='edit'?task.sentence.replace('___',answer):answer))return null;
   return {kind:task.kind,taskIndex:q.taskIndex,english:q.english,russian:task.translation,sentence:task.sentence,answer,choices:q.choices,explanation:task.explanation};
  }
  if(q.kind==='order'&&q.source==='item'){
   const item=itemBank(lesson).find(x=>x[0]===q.english);if(!item)return null;
   const words=item[0].split(/\s+/);if(words.length<4||!Array.isArray(q.choices)||q.choices.length!==words.length||[...q.choices].sort().join('\u0000')!==[...words].sort().join('\u0000'))return null;
   return {kind:'order',source:'item',english:item[0],russian:item[1],answer:item[0],choices:q.choices,explanation:explanations[item[0]]||lesson.tip};
  }
  if(typeof q.reverse!=='boolean')return null;const bank=itemBank(lesson),item=bank.find(x=>x[0]===q.english);if(!item)return null;const valid=bank.map(x=>x[q.reverse?0:1]);if(!Array.isArray(q.choices)||q.choices.length!==4||new Set(q.choices).size!==4||q.choices.some(x=>!valid.includes(x))||!q.choices.includes(item[q.reverse?0:1]))return null;return {english:item[0],russian:item[1],emoji:item[2],explanation:explanations[item[0]],reverse:q.reverse,answer:item[q.reverse?0:1],choices:q.choices}};
 if(!Array.isArray(raw.questions)||raw.questions.length<1||raw.questions.length>64)return null;const questions=raw.questions.map(question);if(questions.some(q=>!q))return null;
 const mistakes=Array.isArray(raw.mistakes)?raw.mistakes.map(question):[];if(mistakes.length>64||mistakes.some(q=>!q))return null;
 const index=raw.index,steps=raw.steps,correct=raw.correct,selected=raw.selected;
 if(!Number.isInteger(index)||index<0||index>10000||(!world.steps||raw.practice||lesson.tasks||lesson.mode)&&index>=questions.length||!Number.isInteger(steps)||steps<0||steps>(world.steps||0)||!Number.isInteger(correct)||correct<0||correct>index+1||selected!==null&&(!Number.isInteger(selected)||selected<0||selected>3))return null;
 const current=questions[index%questions.length],draft=raw.draft??null;
 if(current.kind==='edit'&&draft!==null&&(!Number.isInteger(draft)||draft<0||draft>=4))return null;
 if(current.kind==='order'&&draft!==null&&(!Array.isArray(draft)||draft.some(n=>!Number.isInteger(n)||n<0||n>=current.choices.length)||new Set(draft).size!==draft.length))return null;
 return {lesson,world,questions,index,correct,steps,selected,draft,mistakes,practice:raw.practice===true};
}catch{return null}}
let state=load(),view='map',session=readSession(),selectedWorld=0,introWorld=null;
const main=document.getElementById('appMain');
const done=s=>lessons.filter(l=>[1,2,3].includes(s.scores[l.id])).length;
const total=s=>lessons.reduce((a,l)=>a+([1,2,3].includes(s.scores[l.id])?s.scores[l.id]:0),0)+s.bonus;
function save(){try{localStorage.setItem('slovolet-v1',JSON.stringify(state))}catch{}}
function saveSession(){if(!session)return;try{localStorage.setItem('slovolet-session-v1',JSON.stringify({lessonId:session.lesson.id,questions:session.questions,index:session.index,correct:session.correct,steps:session.steps,selected:session.selected,draft:session.draft,mistakes:session.mistakes,practice:session.practice}))}catch{}}
function clearSession(){try{localStorage.removeItem('slovolet-session-v1')}catch{}}
function updateChrome(){main.classList.toggle('playing-map',Boolean(session?.world?.steps&&!session.practice&&!session.lesson.tasks&&!session.lesson.mode));document.querySelector('.bottom-nav').classList.toggle('hidden-while-playing',Boolean(session?.world?.steps&&!session.practice&&!session.lesson.tasks&&!session.lesson.mode));document.getElementById('starCount').textContent=total(state);document.getElementById('streakCount').textContent=state.streak;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view&&!session))}
function render(){updateChrome();if(session){renderQuestion();return}if(view==='rewards')renderRewards();else if(view==='profile')renderProfile();else if(view==='board')renderWorldBoard(selectedWorld);else renderMap()}
const mapRoutes={
 forest:[[50,94],[70,82],[31,72],[68,61],[34,50],[71,38],[33,26],[64,12]],
 city:[[52,94],[65,82],[31,70],[62,59],[30,48],[64,37],[36,26],[68,13]],
 space:[[52,94],[63,82],[29,71],[70,60],[31,48],[68,36],[32,25],[62,12]]
};
function mapPoint(world,cell,total){
 const a=mapRoutes[world.setting],segments=a.slice(1).map((p,i)=>Math.hypot(p[0]-a[i][0],p[1]-a[i][1]));
 const distance=segments.reduce((n,x)=>n+x,0)*(cell/total);let travelled=0;
 for(let i=0;i<segments.length;i++){if(distance<=travelled+segments[i]||i===segments.length-1){const t=Math.min(1,Math.max(0,(distance-travelled)/segments[i]));return {x:a[i][0]+(a[i+1][0]-a[i][0])*t,y:a[i][1]+(a[i+1][1]-a[i][1])*t}}travelled+=segments[i]}
}
function boardHTML(world,position,fromPosition){
 const total=world.lessons.length*world.steps,active=mapPoint(world,position,total),begin=mapPoint(world,fromPosition??position,total);
 const nodes=Array.from({length:total+1},(_,i)=>{const p=mapPoint(world,i,total);return `<span class="board-cell ${i===position?'is-current':i<position?'is-passed':''} ${i%world.steps===0?'checkpoint':''}" style="left:${p.x}%;top:${p.y}%" aria-hidden="true">${i===0?'▶':i===total?'★':i}</span>`}).join('');
 return `<div class="adventure-map ${world.setting}" aria-label="Карта «${world.name}»: ${total} клеток, герой на клетке ${position}"><div class="map-picture"><img src="./${world.image.replace('.png','.webp')}" data-fallback="./${world.image}" alt="" decoding="async" loading="eager"></div>${nodes}<div class="board-hero" id="boardHero" style="left:${begin.x}%;top:${begin.y}%" aria-hidden="true">${world.character}</div></div>`
}
function wireMapImage(){const img=main.querySelector('.map-picture img');if(img)img.onerror=()=>{if(img.dataset.fallback){const fallback=img.dataset.fallback;img.dataset.fallback='';img.src=fallback}}}
function introSeen(){try{return JSON.parse(localStorage.getItem('slovolet-intros-v1'))||[]}catch{return []}}
function openBoard(index){selectedWorld=index;view='board';session=null;introWorld=introSeen().includes(index)?null:index;render();window.scrollTo(0,0)}
function renderWorldBoard(index){
 const world=worlds[index],resume=readSession(),saved=resume?.world===world?resume:null;
 const stage=Math.max(0,world.lessons.findIndex(l=>!state.scores[l.id]));const lesson=saved?.lesson||world.lessons[stage];const lessonIndex=world.lessons.indexOf(lesson);const position=lessonIndex*world.steps+(saved?.steps||0);
 main.innerHTML=`<div class="board-heading"><button class="secondary" id="backToLevels" type="button">← Уровни</button><span>⭐ ${world.lessons.filter(l=>state.scores[l.id]).length}/${world.lessons.length}</span></div><h1 class="page-title">${world.name}</h1><p class="muted">${world.heroName} ждёт тебя на карте. Каждый верный ответ — шаг к цели.</p><div class="board-action"><strong>${saved?'Продолжить':`Этап ${lessonIndex+1}: ${lesson.name}`}</strong><button class="primary" id="boardPlay" type="button">${saved?'Продолжить →':'Играть →'}</button></div><button class="secondary wide" id="boardLearn" type="button">📖 Узнать слова перед игрой</button>${boardHTML(world,position)}<p class="notice">Нажми «Играть» и помоги герою пройти путь. Верный ответ — вперёд, ошибка — назад.</p>${introWorld===index?`<div class="intro-shade"></div><section class="intro-popup" role="dialog" aria-modal="true" aria-labelledby="introTitle"><div class="intro-face">${world.character}</div><h2 id="introTitle">Я ${world.heroName}!</h2><p>${world.intro}</p><button class="primary wide" id="introGo" type="button">В путь! →</button></section>`:''}`;
 wireMapImage();
 if(index===0){
  const games=world.lessons.filter(l=>l.mode);
  main.querySelector('.adventure-map').insertAdjacentHTML('afterend',`<h2 class="section-title">Азбука и счёт</h2><p class="muted">Выбери любую группу, послушай буквы и числа, затем сыграй.</p><div class="preschool-lesson-grid">${games.map(l=>`<button type="button" data-preschool="${l.id}" class="${state.scores[l.id]?'completed':''}">${l.icon} ${l.name}<span>${state.scores[l.id]?'⭐'.repeat(state.scores[l.id]):'Открыть карточки →'}</span></button>`).join('')}</div>`);
  main.querySelectorAll('[data-preschool]').forEach(b=>b.onclick=()=>openLesson(b.dataset.preschool));
 }
 main.querySelector('#backToLevels').onclick=()=>{introWorld=null;view='map';render();window.scrollTo(0,0)};
 main.querySelector('#boardPlay').onclick=()=>saved?continueSession(saved):start(lesson.id);
 main.querySelector('#boardLearn').onclick=()=>openLesson(lesson.id);
 if(introWorld===index)main.querySelector('#introGo').onclick=()=>{introWorld=null;try{localStorage.setItem('slovolet-intros-v1',JSON.stringify([...new Set([...introSeen(),index])]))}catch{}renderWorldBoard(index)};
}
function renderMap(){
  const next=lessons.find(l=>!state.scores[l.id]),resume=readSession();
  const labels=['Дошкольники','1–2 класс','3–4 класс','5–6 класс','7–9 класс','10–11 класс'];
  main.innerHTML=`<div class="intro"><p class="eyebrow">Игровое путешествие</p><h1 class="page-title">Выбери свой уровень</h1><p class="muted">Для младших — настоящие карты приключений. Для старших — задания на английском.</p></div><div class="grade-pills" aria-label="Выбрать класс">${worlds.map((w,i)=>`<button type="button" data-jump="${i}">${labels[i]}</button>`).join('')}</div><div class="start-card"><p>${resume?`Сохранено: ${resume.world.ages}`:done(state)===0?'Твоё путешествие начинается':`Пройдено ${done(state)} из ${lessons.length} уроков`}</p><h2>${resume?`Продолжить: ${resume.lesson.name}`:next?`Следующий урок: ${next.name}`:'Все уроки пройдены! Можно повторить любимый.'}</h2><button type="button" id="continue">${resume?'Продолжить →':next?'Играть →':'Выбрать урок →'}</button></div><h2 class="section-title">Карта уровней</h2>${worlds.map((w,i)=>`<section class="world" id="world-${i}"><div class="world-head"><span class="world-symbol">${w.icon}</span><div><h2>${w.name}</h2><p>${w.ages}</p></div></div>${w.steps?`<div class="board-entry"><p>${w.character} ${w.heroName} · ${w.lessons.length} этапов приключения</p><button class="secondary wide" type="button" data-board="${i}">Открыть карту →</button></div>`:`<div class="lesson-list">${w.lessons.map(l=>`<button type="button" class="lesson-row" data-lesson="${l.id}"><span class="lesson-icon">${l.icon}</span><span class="lesson-text"><strong>${l.name}</strong><small>${resume?.lesson.id===l.id?'Продолжить с сохранённого места':state.scores[l.id]?'Повторить материал и задания':'Сначала изучи, затем тренируйся'}</small></span><span class="lesson-score">${state.scores[l.id]?'⭐'.repeat(state.scores[l.id]):'→'}</span></button>`).join('')}</div>`}</section>`).join('')}`;
  main.querySelector('#continue').onclick=()=>resume?continueSession(resume):next?worlds.find(w=>w.lessons.includes(next)).steps?openBoard(worlds.findIndex(w=>w.lessons.includes(next))):start(next.id):main.querySelector('.world').scrollIntoView({behavior:'smooth'});
  main.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>resume?.lesson.id===b.dataset.lesson?continueSession(resume):openLesson(b.dataset.lesson));main.querySelectorAll('[data-board]').forEach(b=>b.onclick=()=>openBoard(Number(b.dataset.board)));
  main.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>document.getElementById('world-'+b.dataset.jump).scrollIntoView({behavior:'smooth'}));
}
function openLesson(id){
 const lesson=lessons.find(l=>l.id===id);if(!lesson)return;
 const world=worlds.find(w=>w.lessons.includes(lesson));session=null;view='study';updateChrome();
 const entries=lesson.tasks?lesson.tasks.map(t=>({english:t.kind==='edit'?t.sentence.replace('___',t.answer):t.words.join(' '),russian:t.translation,note:t.explanation})):itemBank(lesson).map(item=>({english:lesson.mode==='letters'?`${item[0]} ${item[1]}`:item[0],spoken:item[0],russian:lesson.mode==='letters'?'Большая и маленькая буква':lesson.mode?`Число ${item[1]}`:item[1],emoji:item[2],note:explanations[item[0]]}));
 const special=exceptions[id]||[];
 main.innerHTML=`<button type="button" class="secondary" id="studyBack">← К урокам</button><p class="eyebrow study-eyebrow">${world.ages}</p><h1 class="page-title">${lesson.icon} ${lesson.name}</h1><p class="muted">Сначала посмотри примеры. Нажми 🔊, чтобы услышать английский, затем переходи к заданиям.</p><div class="lesson-tip study-rule">💡 ${lesson.tip}</div>${special.length?`<h2 class="section-title">Запомни исключения</h2><div class="exception-list">${special.map(([form,meaning,note])=>`<article class="exception-item"><strong>${form}</strong><span>${meaning}</span><small>${note}</small></article>`).join('')}</div>`:''}<h2 class="section-title">Разбираем вместе</h2><div class="study-list">${entries.map((entry,i)=>`<article class="study-item"><span class="study-emoji" aria-hidden="true">${entry.emoji||'✦'}</span><div><strong>${entry.english}</strong><span>${entry.russian}</span>${entry.note?`<small>${entry.note}</small>`:''}</div><button class="sound study-sound" type="button" data-say="${i}" aria-label="Послушать: ${entry.english}">🔊</button></article>`).join('')}</div><div class="study-footer"><button class="primary wide" type="button" id="studyStart">${readSession()?.lesson.id===id?'Продолжить задания →':'Потренироваться →'}</button></div>`;
 main.querySelector('#studyBack').onclick=()=>returnToLevel(lesson);
 main.querySelectorAll('[data-say]').forEach(b=>b.onclick=()=>{const word=entries[Number(b.dataset.say)].spoken||entries[Number(b.dataset.say)].english;speak(lesson.mode==='letters'?`Letter ${word}`:word)});
 main.querySelector('#studyStart').onclick=()=>{const saved=readSession();saved?.lesson.id===id?continueSession(saved):start(id)};
 window.scrollTo(0,0);
}
function renderRewards(){main.innerHTML=`<p class="eyebrow">Коллекция</p><h1 class="page-title">Мои награды</h1><p class="muted">Открывай значки за старание и новые знания.</p><div class="reward-grid" style="margin-top:22px">${awards.map(a=>`<div class="reward ${a.check(state)?'':'dim'}"><div class="emoji">${a.icon}</div><strong>${a.name}</strong><small>${a.check(state)?'Получено!':a.hint}</small></div>`).join('')}</div><div class="info-card"><h2>Твои звёзды ⭐</h2><div class="big-number">${total(state)}</div><p>За каждый урок можно получить до 3 звёзд. За первый идеальный результат — ещё 1 бонусную звезду.</p></div>`}
function renderProfile(){let n=done(state);const pending=lessons.filter(l=>Array.isArray(state.errors[l.id])&&state.errors[l.id].length);main.innerHTML=`<p class="eyebrow">Мой путь</p><h1 class="page-title">Прогресс</h1><div class="info-card"><h2>Пройденные уроки</h2><div class="big-number">${n} / ${lessons.length}</div><div class="meter" aria-label="Пройдено ${n} из ${lessons.length} уроков"><span style="width:${n/lessons.length*100}%"></span></div><p>Маленький шаг каждый день — уже победа.</p></div><div class="info-card"><h2>Серия дней 🔥</h2><div class="big-number">${state.streak}</div><p>Пройди хотя бы один урок в новый день, чтобы продолжить серию.</p></div><div class="info-card"><h2>Повторить сложное 🧠</h2><p>${pending.length?'Выбери тему и попробуй ещё раз. Правильные ответы убирают задания из списка.':'Пока ошибок для повторения нет. Новые сложные слова появятся здесь.'}</p>${pending.map(l=>`<button type="button" class="review-row" data-review="${l.id}">${l.icon} ${l.name}<span>${state.errors[l.id].length} →</span></button>`).join('')}</div><div class="info-card setting"><div><h2>Звук слов 🔊</h2><p>Произношение на английском</p></div><button type="button" class="secondary" id="soundToggle">${state.sound?'Вкл.':'Выкл.'}</button></div><p class="notice">Прогресс и место в текущем уроке сохраняются на этом устройстве. После очистки данных браузера они исчезнут.</p><button type="button" class="small-link" id="reset">Начать заново</button>`;main.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>reviewLesson(b.dataset.review));main.querySelector('#soundToggle').onclick=()=>{state.sound=!state.sound;save();render()};main.querySelector('#reset').onclick=()=>{if(confirm('Удалить все звёзды, награды и пройденные уроки на этом устройстве?')){state={scores:{},errors:{},bonus:0,lastDay:'',streak:0,sound:state.sound};clearSession();save();render()}}}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function taskQuestion(l,i){const t=l.tasks[i];return {kind:t.kind,taskIndex:i,english:t.kind==='edit'?t.sentence.replace('___',t.answer):t.words.join(' '),russian:t.translation,sentence:t.sentence,answer:t.kind==='edit'?t.answer:t.words.join(' '),choices:shuffle([...(t.kind==='edit'?t.choices:t.words)]),explanation:t.explanation}}
function translationQuestion(l,item,reverse){const bank=itemBank(l),other=shuffle(bank.filter(x=>x[0]!==item[0]));const pool=[item,...other.slice(0,3)];return {english:item[0],russian:item[1],emoji:item[2],explanation:explanations[item[0]],reverse,answer:item[reverse?0:1],choices:shuffle(pool.map(x=>x[reverse?0:1]))}}
function orderQuestion(l,item){return {kind:'order',source:'item',english:item[0],russian:item[1],answer:item[0],choices:shuffle(item[0].split(/\s+/)),explanation:explanations[item[0]]||l.tip}}
function isAdvanced(l){return worlds.slice(3).some(w=>w.lessons.includes(l))}
function stageLabel(s){if(s.practice)return '';if(s.lesson.id==='grade34-bridge')return `<p class="stage-label">${s.index<6?'① Выбери нужную форму':'② Собери предложение'}</p>`;if(!isAdvanced(s.lesson))return '';return `<p class="stage-label">${s.index<3?`① Разминка · ${s.lesson.tasks?'выбери форму':'выбери перевод'}`:s.index<6?`② Практика · ${s.lesson.tasks?'вставь нужное слово':'переведи на английский'}`:'③ Вызов · собери предложение'}</p>`}
function makeQuestions(l,walk=false){
 if(l.mode)return shuffle(itemBank(l)).map(item=>translationQuestion(l,item,false));
 if(l.tasks){
  if(!isAdvanced(l))return (l.id==='grade34-bridge'?l.tasks.map((_,i)=>i):shuffle(l.tasks.map((_,i)=>i)).slice(0,8)).map(i=>taskQuestion(l,i));
  const edits=l.tasks.map((t,i)=>t.kind==='edit'?i:null).filter(i=>i!==null),orders=l.tasks.map((t,i)=>t.kind==='order'?i:null).filter(i=>i!==null);
  const split=Math.ceil(edits.length/2);return [...shuffle(edits.slice(0,split)).slice(0,3),...shuffle(edits.slice(split)).slice(0,3),...shuffle(orders).slice(0,2)].map(i=>taskQuestion(l,i));
 }
 const bank=shuffle(itemBank(l));
 if(isAdvanced(l)){const first=Array.from({length:3},(_,i)=>bank[i%bank.length]),second=Array.from({length:3},(_,i)=>bank[(i+3)%bank.length]),hard=shuffle(bank.filter(x=>x[0].split(/\s+/).length>=4)).slice(0,2);return [...first.map(item=>translationQuestion(l,item,false)),...second.map(item=>translationQuestion(l,item,true)),...hard.map(item=>orderQuestion(l,item))]}
 const examples=Array.from({length:8},(_,i)=>bank[i%bank.length]);return shuffle([...examples.slice(0,4).map(item=>translationQuestion(l,item,false)),...examples.slice(4).map(item=>translationQuestion(l,item,true))]);
}
function replaceQuestion(){const s=session;if(!s||s.selected!==null)return;const index=s.index%s.questions.length,current=s.questions[index];let replacement;
 if(s.lesson.tasks){const unused=s.lesson.tasks.map((_,i)=>i).filter(i=>!s.questions.some(q=>q.taskIndex===i));if(unused.length)replacement=taskQuestion(s.lesson,unused[Math.floor(Math.random()*unused.length)])}
 else{const unused=itemBank(s.lesson).filter(item=>!s.questions.some(q=>q.english===item[0]));if(unused.length)replacement=translationQuestion(s.lesson,unused[Math.floor(Math.random()*unused.length)],current.reverse)}
 if(replacement){s.questions[index]=replacement}
 else{const future=s.questions.findIndex((q,i)=>i>index&&q.english!==current.english);if(future>=0)[s.questions[index],s.questions[future]]=[s.questions[future],s.questions[index]];
  else if(s.lesson.tasks){const candidates=s.lesson.tasks.map((_,i)=>i).filter(i=>i!==current.taskIndex);s.questions[index]=taskQuestion(s.lesson,candidates[Math.floor(Math.random()*candidates.length)])}
  else{const candidates=itemBank(s.lesson).filter(item=>item[0]!==current.english&&item[0]!==s.questions[(index-1+s.questions.length)%s.questions.length].english);const pool=candidates.length?candidates:itemBank(s.lesson).filter(item=>item[0]!==current.english);s.questions[index]=translationQuestion(s.lesson,pool[Math.floor(Math.random()*pool.length)],current.reverse)}
 }
 s.draft=null;saveSession();renderQuestion();
}
function continueSession(saved){session=saved;render();window.scrollTo(0,0)}
function start(id){const lesson=lessons.find(l=>l.id===id);if(!lesson)return;const world=worlds.find(w=>w.lessons.includes(lesson));session={lesson,world,questions:makeQuestions(lesson,Boolean(world.steps)),index:0,correct:0,steps:0,selected:null,draft:null,mistakes:[],practice:false};saveSession();window.scrollTo(0,0);render()}
function returnToLevel(lesson){const index=worlds.findIndex(w=>w.lessons.includes(lesson));session=null;if(worlds[index].steps){selectedWorld=index;view='board';render();window.scrollTo(0,0)}else{view='map';render();const target=document.getElementById(`world-${index}`);if(target)target.scrollIntoView({behavior:'instant',block:'start'})}}
function speak(word){if(!state.sound||!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(word);u.lang='en-US';u.rate=.78;window.speechSynthesis.speak(u)}
function renderWalkQuestion(s,fromPosition){
 const world=s.world,position=world.lessons.indexOf(s.lesson)*world.steps+s.steps,total=world.lessons.length*world.steps,q=s.questions[s.index%s.questions.length];
 main.innerHTML=`<div class="board-heading"><button class="secondary" id="leave" type="button">← К карте</button><span>${s.lesson.name} · ${s.steps}/${world.steps} шагов</span></div>${boardHTML(world,position,fromPosition)}<div class="question-shade"></div><section class="challenge-sheet" aria-label="Задание на карте"><p class="eyebrow">${world.character} ${world.heroName} · ${s.lesson.name}</p><p class="walk-hint">${s.lesson.tip}</p><div class="question-card">${q.emoji?`<div class="big-emoji" aria-hidden="true">${q.emoji}</div>`:''}<p class="instruction">${q.reverse?'Как сказать по-английски?':'Что это значит?'}</p><h1 class="target">${q.reverse?q.russian:q.english}</h1><button type="button" class="sound" id="speak" aria-label="Послушать английское произношение">🔊</button></div>${s.selected===null?'<button class="change-task" id="changeTask" type="button">↻ Другое задание</button>':''}<div class="options ${q.choices.every(c=>c.length<19)?'compact-options':''}">${q.choices.map((c,i)=>`<button class="option" data-choice="${i}" type="button" ${s.selected!==null?'disabled':''}>${c}</button>`).join('')}</div><div id="result"></div><button class="primary wide" id="next" type="button" ${s.selected===null?'disabled':''}>${s.steps===world.steps?'Дойти до цели':'Следующий шаг →'}</button></section>`;
 wireMapImage();
 main.querySelector('#leave').onclick=()=>returnToLevel(s.lesson);main.querySelector('#speak').onclick=()=>speak(q.english);if(s.selected===null)main.querySelector('#changeTask').onclick=replaceQuestion;main.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>choose(Number(b.dataset.choice)));main.querySelector('#next').onclick=next;if(s.selected!==null)paintAnswer();
 requestAnimationFrame(()=>{const hero=main.querySelector('#boardHero');if(fromPosition!==undefined){const p=mapPoint(world,position,total);hero.style.left=p.x+'%';hero.style.top=p.y+'%'}if(window.matchMedia('(max-width: 520px)').matches)return;const rect=hero.getBoundingClientRect();const delta=rect.top-window.innerHeight*.2;if(Math.abs(delta)>10)window.scrollBy({top:delta,behavior:fromPosition===undefined?'instant':'smooth'})});
}
function renderPreschool(s,q){
 const mode=s.lesson.mode,heading=mode==='letters'?'Послушай букву и найди её маленькую пару':mode==='count'?'Посчитай яблоки и выбери число':'Послушай число и выбери цифры';
 const picture=mode==='count'?(q.english==='zero'?'🧺 Пустая корзина':q.emoji):mode==='letters'?q.emoji:'🔢';
 main.innerHTML=`<div class="play-top"><button type="button" class="back" id="leave" aria-label="К урокам">×</button><div class="progress-rail" role="progressbar" aria-label="Прогресс урока" aria-valuenow="${s.index}" aria-valuemin="0" aria-valuemax="${s.questions.length}"><div class="progress-fill" style="width:${s.index/s.questions.length*100}%"></div></div><span class="step">${s.index+1}/${s.questions.length}</span></div><p class="eyebrow">${s.lesson.name}</p><section class="question-card preschool-card"><p class="instruction">${heading}</p><div class="preschool-picture" aria-hidden="true">${picture}</div><button type="button" class="sound preschool-sound" id="speak" aria-label="Послушать букву или число">🔊 Послушать</button></section><div class="options preschool-options">${q.choices.map((choice,i)=>`<button class="option" data-choice="${i}" type="button" ${s.selected!==null?'disabled':''}>${choice}</button>`).join('')}</div><div id="result"></div><div class="play-actions"><button type="button" class="primary wide" id="next" ${s.selected===null?'disabled':''}>${s.index===s.questions.length-1?'Завершить урок':'Дальше →'}</button></div>`;
 main.querySelector('#leave').onclick=()=>returnToLevel(s.lesson);
 main.querySelector('#speak').onclick=()=>speak(mode==='letters'?`Letter ${q.english}`:q.english);
 main.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>choose(Number(b.dataset.choice)));
 main.querySelector('#next').onclick=next;if(s.selected!==null)paintAnswer();
}
function renderQuestion(fromPosition){
 const s=session,walk=Boolean(s.world?.steps&&!s.practice&&!s.lesson.tasks&&!s.lesson.mode),q=s.questions[s.index%s.questions.length],len=s.questions.length;
 if(walk){renderWalkQuestion(s,fromPosition);return}
 if(s.lesson.mode){renderPreschool(s,q);return}
 if(q.kind){renderWorkshop(s,q);return}
 const progress=walk?s.steps:s.index,goal=walk?s.world.steps:len;
 const path=walk?`<div class="walk-scene ${s.world.setting}" role="img" aria-label="${s.world.name}: герой прошёл ${s.steps} из ${goal} шагов"><div class="scene-label">${s.world.setting==='forest'?'🌲 Лесная тропа 🌳':s.world.setting==='city'?'🏘️ Город приключений 🏙️':'✨ Космический путь 🌟'}</div><div class="walk-path">${Array.from({length:goal+1},(_,n)=>`<span class="path-node ${n===s.steps?'here':n<s.steps?'passed':''}" aria-hidden="true">${n===s.steps?s.world.character:n===goal?s.world.destination:n<s.steps?'✓':'·'}</span>`).join('')}</div><p>${s.steps===goal?'Цель достигнута!':`До цели ещё ${goal-s.steps} ${goal-s.steps===1?'шаг':'шага'}`}</p></div>`:'';
 main.innerHTML=`<div class="play-top"><button type="button" class="back" id="leave" aria-label="К урокам этого уровня">×</button><div class="progress-rail" role="progressbar" aria-label="Прогресс урока" aria-valuenow="${progress}" aria-valuemin="0" aria-valuemax="${goal}"><div class="progress-fill" style="width:${progress/goal*100}%"></div></div><span class="step">${walk?`${s.steps}/${goal} шагов`:`${s.index+1}/${len}`}</span></div><p class="eyebrow">${s.lesson.name}</p>${stageLabel(s)}${path}${s.lesson.tip?`<p class="lesson-tip">💡 ${s.lesson.tip}</p>`:''}<section class="question-card">${q.emoji?`<div class="big-emoji" aria-hidden="true">${q.emoji}</div>`:''}<p class="instruction">${q.reverse?'Как сказать по-английски?':'Что это значит?'}</p><h1 class="target">${q.reverse?q.russian:q.english}</h1><button type="button" class="sound" id="speak" aria-label="Послушать английское произношение" title="Послушать слово">🔊</button></section>${s.selected===null&&!isAdvanced(s.lesson)?'<button class="change-task" id="changeTask" type="button">↻ Другое задание</button>':''}<div class="options">${q.choices.map((c,i)=>`<button class="option" data-choice="${i}" type="button" ${s.selected!==null?'disabled':''}>${c}</button>`).join('')}</div><div id="result"></div><div class="play-actions"><button type="button" class="primary wide" id="next" ${s.selected===null?'disabled':''}>${walk?s.steps===goal?'Завершить маршрут':'Дальше →':s.index===len-1?'Завершить урок':'Дальше →'}</button></div>`;
 main.querySelector('#leave').onclick=()=>returnToLevel(s.lesson);main.querySelector('#speak').onclick=()=>speak(q.english);if(main.querySelector('#changeTask'))main.querySelector('#changeTask').onclick=replaceQuestion;main.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>choose(Number(b.dataset.choice)));main.querySelector('#next').onclick=next;if(s.selected!==null)paintAnswer();
}
function renderWorkshop(s,q){
 const progress=s.index,len=s.questions.length,order=q.kind==='order',draft=s.draft??(order?[]:null);
 const preview=order?draft.map(i=>q.choices[i]).join(' '):q.sentence.replace('___',draft===null?'_____':q.choices[draft]);
 const options=order?`<div class="word-bank" aria-label="Слова для предложения">${q.choices.map((word,i)=>`<button type="button" class="word-chip" data-word="${i}" ${draft.includes(i)||s.selected!==null?'disabled':''}>${word}</button>`).join('')}</div><p class="notice">Нажимай на слова по порядку. Чтобы убрать слово, нажми на него в предложении.</p><div class="selected-words" aria-label="Собранное предложение">${draft.map((i,n)=>`<button type="button" class="word-chip chosen" data-remove="${n}" ${s.selected!==null?'disabled':''}>${q.choices[i]} ×</button>`).join('')||'<span class="muted">Выбери первое слово выше</span>'}</div>`:`<div class="options">${q.choices.map((word,i)=>`<button class="option ${draft===i?'picked':''}" type="button" data-pick="${i}" aria-pressed="${draft===i}" ${s.selected!==null?'disabled':''}>${word}</button>`).join('')}</div>`;
 main.innerHTML=`<div class="play-top"><button type="button" class="back" id="leave" aria-label="К урокам этого уровня">×</button><div class="progress-rail" role="progressbar" aria-label="Прогресс урока" aria-valuenow="${progress}" aria-valuemin="0" aria-valuemax="${len}"><div class="progress-fill" style="width:${progress/len*100}%"></div></div><span class="step">${s.index+1}/${len}</span></div><p class="eyebrow">${s.lesson.name}</p>${stageLabel(s)}<p class="lesson-tip">💡 ${s.lesson.tip}</p><section class="question-card workshop-card"><p class="instruction">${order?'Собери предложение по-английски':'Выбери слово или форму и вставь в пропуск'}</p><p class="translation">${q.russian}</p><h1 class="target" aria-live="polite">${preview}</h1></section>${s.selected===null&&!isAdvanced(s.lesson)?'<button class="change-task" id="changeTask" type="button">↻ Другое задание</button>':''}${options}<div id="result"></div><div class="play-actions">${s.selected===null?`<button type="button" class="primary wide" id="check" ${(order?draft.length!==q.choices.length:draft===null)?'disabled':''}>Проверить предложение</button>`:`<button type="button" class="primary wide" id="next">${s.index===len-1?'Завершить урок':'Дальше →'}</button>`}</div>`;
 main.querySelector('#leave').onclick=()=>returnToLevel(s.lesson);if(main.querySelector('#changeTask'))main.querySelector('#changeTask').onclick=replaceQuestion;
 main.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{s.draft=Number(b.dataset.pick);saveSession();renderQuestion()});
 main.querySelectorAll('[data-word]').forEach(b=>b.onclick=()=>{s.draft=[...(s.draft||[]),Number(b.dataset.word)];saveSession();renderQuestion()});
 main.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{s.draft=s.draft.filter((_,i)=>i!==Number(b.dataset.remove));saveSession();renderQuestion()});
 if(s.selected===null)main.querySelector('#check').onclick=submitWorkshop;else{paintAnswer();main.querySelector('#next').onclick=next}
}
function errorKey(q){return q.source==='item'?`order:${q.english}`:q.kind?`task:${q.taskIndex}`:`word:${q.reverse?'ru':'en'}:${q.english}`}
function recordAnswer(s,q,right){
 const key=errorKey(q),existing=Array.isArray(state.errors[s.lesson.id])?state.errors[s.lesson.id]:[];
 const updated=right?existing.filter(x=>x!==key):[...new Set([...existing,key])];
 if(updated.length)state.errors[s.lesson.id]=updated;else delete state.errors[s.lesson.id];save();
}
function reviewLesson(id){
 const lesson=lessons.find(l=>l.id===id),world=worlds.find(w=>w.lessons.includes(lesson));
 const keys=Array.isArray(state.errors[id])?state.errors[id]:[];
 const questions=keys.map(key=>{
  if(key.startsWith('task:')&&lesson.tasks){const i=Number(key.slice(5));return Number.isInteger(i)&&lesson.tasks[i]?taskQuestion(lesson,i):null}
  if(key.startsWith('order:')&&!lesson.tasks){const item=itemBank(lesson).find(x=>x[0]===key.slice(6));return item?orderQuestion(lesson,item):null}
  const match=/^word:(en|ru):(.*)$/.exec(key);if(!match||lesson.tasks)return null;
  const item=itemBank(lesson).find(x=>x[0]===match[2]);return item?translationQuestion(lesson,item,match[1]==='ru'):null;
 }).filter(Boolean);
 if(!questions.length)return;
 session={lesson,world,questions:shuffle(questions),index:0,correct:0,steps:0,selected:null,draft:null,mistakes:[],practice:true};saveSession();render();window.scrollTo(0,0);
}
function submitWorkshop(){const s=session,q=s.questions[s.index%s.questions.length];if(!q.kind||s.selected!==null)return;const order=q.kind==='order',draft=s.draft;if(order?(!Array.isArray(draft)||draft.length!==q.choices.length):draft===null)return;const response=order?draft.map(i=>q.choices[i]).join(' '):q.choices[draft];const right=response===q.answer;s.selected=right?0:1;recordAnswer(s,q,right);if(right)s.correct++;else if(!s.mistakes.some(x=>errorKey(x)===errorKey(q)))s.mistakes.push(q);saveSession();renderQuestion()}
function choose(i){if(session.selected!==null)return;const s=session,q=s.questions[s.index%s.questions.length],right=q.choices[i]===q.answer;const oldPosition=s.world?.steps&&!s.practice&&!s.lesson.mode?s.world.lessons.indexOf(s.lesson)*s.world.steps+s.steps:undefined;s.selected=i;recordAnswer(s,q,right);if(right){s.correct++;if(s.world?.steps&&!s.practice&&!s.lesson.mode)s.steps++}else{if(!s.mistakes.some(x=>x.english===q.english&&x.reverse===q.reverse))s.mistakes.push(q);if(s.world?.steps&&!s.practice&&!s.lesson.mode)s.steps=Math.max(0,s.steps-1)}saveSession();renderQuestion(oldPosition)}
function paintAnswer(){const s=session,q=s.questions[s.index%s.questions.length],right=q.kind?s.selected===0:q.choices[s.selected]===q.answer,walking=s.world?.steps&&!s.practice&&!s.lesson.mode;main.querySelectorAll('[data-choice]').forEach(b=>{let v=q.choices[Number(b.dataset.choice)];b.disabled=true;if(v===q.answer)b.classList.add('correct');else if(Number(b.dataset.choice)===s.selected)b.classList.add('wrong')});main.querySelector('#result').innerHTML=q.kind?`<div class="feedback ${right?'good':'try'}">${right?'Верно! Предложение получилось 🌟':`Правильно: ${q.english}`}<span class="why">${q.explanation}</span></div>`:`<div class="feedback ${right?'good':'try'}">${right?walking?'Верно! Шаг вперёд 🌟':'Верно! Отличная работа 🌟':`${walking?'Шаг назад. ':''}Правильный ответ: ${q.answer}<span class="why">${q.explanation||s.lesson.tip} Запомни: ${q.english} — ${q.russian}.</span>`}</div>`;main.querySelector('#next').disabled=false}
function next(){const s=session;if(!s||s.selected===null)return;if(s.world?.steps&&!s.practice&&!s.lesson.tasks&&!s.lesson.mode&&s.steps>=s.world.steps){finish();return}if(s.practice||!s.world?.steps||s.lesson.tasks||s.lesson.mode){if(s.index>=s.questions.length-1){finish();return}}s.index++;s.selected=null;s.draft=null;saveSession();renderQuestion();window.scrollTo(0,0)}
function finish(){
 const s=session,walk=Boolean(s.world?.steps&&!s.practice&&!s.lesson.tasks&&!s.lesson.mode),len=walk?s.index+1:s.questions.length,perfect=walk?s.mistakes.length===0:s.correct===len,earned=walk?s.mistakes.length===0?3:s.mistakes.length<=2?2:1:perfect?3:s.correct>=Math.ceil(len*.67)?2:1;let bonus=0;
 if(!s.practice){const previous=state.scores[s.lesson.id]||0;state.scores[s.lesson.id]=Math.max(previous,earned);bonus=perfect&&previous===0?1:0;state.bonus+=bonus;const day=new Date().toLocaleDateString('en-CA');if(state.lastDay!==day){const yesterday=new Date();yesterday.setDate(yesterday.getDate()-1);const prev=yesterday.toLocaleDateString('en-CA');state.streak=state.lastDay===prev?state.streak+1:1;state.lastDay=day}save()}
 session=null;clearSession();updateChrome();main.innerHTML=`<div class="finish"><div class="trophy">${s.practice?'🧠':walk?s.world.destination:earned===3?'🏆':'🎉'}</div><p class="eyebrow">${s.practice?'Повторение ошибок':walk?'Маршрут пройден':`Урок «${s.lesson.name}» пройден`}</p><h1>${perfect?'Идеально!':'Хороший шаг вперёд!'}</h1><p>Правильных ответов: ${s.correct} из ${len}${walk?' попыток':''}</p>${s.practice?'<p>Повторение помогает разобраться в сложных фразах.</p>':`<div class="earned">${'⭐'.repeat(earned)} ${bonus?'+ ⭐ бонус':''}</div>`}<button class="primary wide" id="mapReturn" type="button">К урокам этого уровня</button><div class="empty-space"></div>${s.mistakes.length?'<button class="secondary wide" id="review" type="button">Повторить ошибки</button><div class="empty-space"></div>':''}<button class="secondary wide" id="replay" type="button">${walk?'Пройти маршрут с другими словами':'Пройти урок заново'}</button></div>`;
 main.querySelector('#mapReturn').onclick=()=>returnToLevel(s.lesson);main.querySelector('#replay').onclick=()=>start(s.lesson.id);if(s.mistakes.length)main.querySelector('#review').onclick=()=>{session={lesson:s.lesson,world:s.world,questions:s.mistakes,index:0,correct:0,steps:0,selected:null,draft:null,mistakes:[],practice:true};saveSession();render();window.scrollTo(0,0)};window.scrollTo(0,0);
}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{session=null;view=b.dataset.view;render();window.scrollTo(0,0)});document.querySelector('#homeButton').onclick=()=>{session=null;view='map';render();window.scrollTo(0,0)};render();
